plugins {
    id 'java-library'
}

group = 'com.lura'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api platform('software.amazon.awssdk:bom:2.42.41')
    api 'software.amazon.awssdk:s3'
}
